


class Autogenerated {
  String? postid;
  String? desc;
  String? pvnum;
  String? createdate;
  String? scover;
  String? setname;
  String? cover;
  List<Null>? pics;
  String? clientcover1;
  String? replynum;
  String? topicname;
  String? setid;
  String? seturl;
  String? datetime;
  String? clientcover;
  String? imgsum;
  String? tcover;

  Autogenerated(
      {this.postid,
      this.desc,
      this.pvnum,
      this.createdate,
      this.scover,
      this.setname,
      this.cover,
      this.pics,
      this.clientcover1,
      this.replynum,
      this.topicname,
      this.setid,
      this.seturl,
      this.datetime,
      this.clientcover,
      this.imgsum,
      this.tcover});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    postid = json['postid'];
    desc = json['desc'];
    pvnum = json['pvnum'];
    createdate = json['createdate'];
    scover = json['scover'];
    setname = json['setname'];
    cover = json['cover'];
    if (json['pics'] != null) {
      pics = <Null>[];
      json['pics'].forEach((v) {
    //  Null n = v as Null;
        // pics!.add(Null.fromJson(v));
            
            pics!.add(v);
 
      });
    }
    clientcover1 = json['clientcover1'];
    replynum = json['replynum'];
    topicname = json['topicname'];
    setid = json['setid'];
    seturl = json['seturl'];
    datetime = json['datetime'];
    clientcover = json['clientcover'];
    imgsum = json['imgsum'];
    tcover = json['tcover'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['postid'] = this.postid;
    data['desc'] = this.desc;
    data['pvnum'] = this.pvnum;
    data['createdate'] = this.createdate;
    data['scover'] = this.scover;
    data['setname'] = this.setname;
    data['cover'] = this.cover;
    if (this.pics != null) {
      data['pics'] = this.pics!.map((v) => v.toString()).toList();
    }
    data['clientcover1'] = this.clientcover1;
    data['replynum'] = this.replynum;
    data['topicname'] = this.topicname;
    data['setid'] = this.setid;
    data['seturl'] = this.seturl;
    data['datetime'] = this.datetime;
    data['clientcover'] = this.clientcover;
    data['imgsum'] = this.imgsum;
    data['tcover'] = this.tcover;
    return data;
  }
}
