import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_20240407_code_wall/subview/Autogenerated.dart';
import 'package:flutter_20240407_code_wall/subview/User.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;

import 'mlist/ProductListScreen.dart';
import 'webview_flutter.dart';

/**
 * 列表和网络请求
 */
class listviewJson extends StatefulWidget {
  const listviewJson({super.key});

  @override
  State<listviewJson> createState() => _listviewJsonState();
}

class _listviewJsonState extends State<listviewJson> {
  List<String> dataList = []; 
  List<Autogenerated> auto_dataList = [];

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    // fetchDataFromServer();
    fetchDataFromApi();
  }

  Future<void> fetchDataFromServer() async {
    try {
      final response = await http
          .get(Uri.parse('https://jsonplaceholder.typicode.com/posts'));
      print(
          "------------------------fetchDataFromServer--------------------${response.statusCode}");
      if (response.statusCode == 200) {
        List<dynamic> jsonResponse = jsonDecode(response.body);
        List<String> newDataList = [];
        for (var item in jsonResponse) {
          newDataList.add(item['title']); // 假设服务器返回的数据中有一个'title'字段
        }
        setState(() {
          dataList = newDataList;
        });
      } else {
        throw Exception('Failed to load data from server');
      }
    } catch (e) {
      print('----------------------Error: $e');
    }
  }

  Future<void> fetchDataFromApi() async {
    try {
      final response = await http.get(Uri.parse(
              'https://3g.163.com/photocenter/api/list/0001/00AP0001,3R710001,4T8E0001/30/3.json')
          // ,headers:{"Content-Type": "application/json"}
          );
      print(
          "------------------------fetchDataFromApi--------------------${response.statusCode}");
      if (response.statusCode == 200) {
        List<dynamic> jsonData = json.decode(response.body);
        setState(() {
          auto_dataList =
              jsonData.map((data) => Autogenerated.fromJson(data)).toList();
        });
      } else {
        // Handle error if needed
      }
    } catch (e) {
      print('Error: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    print("---------------build----------------列表和网络请求--------------");

    return Scaffold(
      appBar: AppBar(
        title: Text(
          "列表和网络请求",
          style: TextStyle(fontSize: 16, color: Colors.red),
        ),
        leading: null,
        automaticallyImplyLeading: false,
        centerTitle: true,
      ),
      backgroundColor: Colors.grey,
      body: Column(
        children: [
          Expanded(
              child: ListView.separated(
            itemCount: auto_dataList.length,
            separatorBuilder: (context, index) {
              return Divider(color: Colors.red); // 这里可以自定义分隔线的样式
            },
            itemBuilder: (context, index) {
              String tcover = auto_dataList[index].tcover ?? '';
              // 根据索引决定不同的背景颜色
              Color? backgroundColor =
                  index % 2 == 0 ? Colors.blue[100] : Colors.blue[200];
              return Column(
                children: [
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Column(
                        children: [
                          
                          AspectRatio(
                        aspectRatio: 16 / 9, // this is the ratio
                        child: CachedNetworkImage(
                          // this is to fetch the image
                          imageUrl:
                              auto_dataList[index].cover?.toString() ?? "",
                          fit: BoxFit.cover,
                        ),
                      ),
                      
                    Container(
                    color: backgroundColor,
                    child: ListTile(
                      title: Text('title ${auto_dataList[index].setname}'),
                      subtitle: Text('subtitle ${auto_dataList[index].desc}'),
                      // leading: Image.network(tcover),
                      trailing: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(Icons.star,
                              color:
                                  Colors.orange), // this will give the rating
                          Text('${auto_dataList[index].postid}',
                              style: TextStyle(
                                  fontFamily: 'Poppins',
                                  package: 'Poppins-ExtraLight.ttf')),
                        ],
                      ),



 onTap: () {
    
print("-----------------点击详情--------item-------");
    //  var route = MaterialPageRoute(builder: (context) => WebViewflutter());
    //   Navigator.push(context, route);
     var mdmes= auto_dataList[index];

    Navigator.push(
  context,
  MaterialPageRoute(
    builder: (context) => WebViewflutter(Autog: mdmes),
  ),
);


 },

                    ),
                  ),



                      ],
                      )
                    ),
                  ),
              
                ],
              );
            },
          ))
        ],
      ),
    );
  }
}
